apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: public.ecr.aws/efs-csi-driver/amazon/aws-efs-csi-driver
    newTag: v2.1.2
  - name: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe
    newTag: v2.14.0-eks-1-31-5
  - name: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar
    newTag: v2.12.0-eks-1-31-5
  - name: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner
    newTag: v5.1.0-eks-1-31-5
