apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: amazon/aws-efs-csi-driver
    newTag: v1.2.0
  - name: k8s.gcr.io/sig-storage/csi-provisioner
    newTag: v2.0.3
  - name: k8s.gcr.io/sig-storage/livenessprobe
    newTag: v2.2.0
  - name: k8s.gcr.io/sig-storage/csi-node-driver-registrar
    newTag: v2.1.0
