apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: public.ecr.aws/efs-csi-driver/amazon/aws-efs-csi-driver
    newTag: v2.0.6
  - name: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe
    newTag: v2.13.0-eks-1-30-8
  - name: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar
    newTag: v2.11.0-eks-1-30-8
  - name: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner
    newTag: v5.0.1-eks-1-30-8
