apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: amazon/aws-efs-csi-driver
    newTag: v1.2.1
  - name: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe
    newTag: v2.2.0-eks-1-18-2
  - name: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar
    newTag: v2.1.0-eks-1-18-2
  - name: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner
    newTag: v2.1.1-eks-1-18-2
