apiVersion: v1
appVersion: "1.2.0"
name: aws-efs-csi-driver
description: A Helm chart for AWS EFS CSI Driver
version: 1.2.3
kubeVersion: ">=1.17.0-0"
home: https://github.com/kubernetes-sigs/aws-efs-csi-driver
sources:
  - https://github.com/kubernetes-sigs/aws-efs-csi-driver
keywords:
  - aws
  - efs
  - csi
maintainers:
  - name: leakingtapan
    url: https://github.com/leakingtapan
  - name: krmichel
    url: https://github.com/krmichel
