apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../base
images:
  - name: amazon/aws-efs-csi-driver
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-driver
    newTag: v1.7.7
  - name: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/livenessprobe
    newTag: v2.12.0-eks-1-29-7
  - name: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-node-driver-registrar
    newTag: v2.10.0-eks-1-29-7
  - name: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-provisioner
    newTag: v4.0.0-eks-1-29-7
