apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../base
images:
  - name: public.ecr.aws/efs-csi-driver/amazon/aws-efs-csi-driver
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-driver
    newTag: v2
  - name: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/livenessprobe
    newTag: v2.14.0-eks-1-31-5
  - name: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-node-driver-registrar
    newTag: v2.12.0-eks-1-31-5
  - name: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-provisioner
    newTag: v5.1.0-eks-1-31-5
