name: Release
on:
  pull_request_target:
    types: 
      - closed
    branches:
      - release-*

permissions:
  contents: write # Create releases

jobs:
  release:
    # will only be triggered if PR title begins with [POST-RELEASE v*.*.*]
    name: Release
    runs-on: ubuntu-latest
    permissions: write-all
    if: |
      github.event.pull_request.merged == true && 
      startsWith(github.event.pull_request.title, '[POST-RELEASE')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Extract version
        id: extract-version
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          VERSION=$(echo "$PR_TITLE" | grep -oE '^\[POST-RELEASE v[0-9]+\.[0-9]+\.[0-9]+\]' | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+')
          
          if [ -z "$VERSION" ]; then
            echo "Error: PR title must start with [POST-RELEASE vx.x.x]"
            exit 1
          fi
          
          echo "Extracted VERSION: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          
      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${{ steps.extract-version.outputs.version }}"
          
          gh release create "$tag" --title "$tag" --notes-file - <<EOF
          AWS EFS CSI Driver
          
          ## CHANGELOG
          See [CHANGELOG](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/CHANGELOG-2.x.md) for full list of changes
          EOF
